# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setupJob.ui'
#
# Created: Wed Mar 18 16:54:22 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SetupJobForm(object):
    def setupUi(self, SetupJobForm):
        SetupJobForm.setObjectName("SetupJobForm")
        SetupJobForm.resize(911, 589)
        self.horizontalLayout = QtGui.QHBoxLayout(SetupJobForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutPreview = QtGui.QVBoxLayout()
        self.layoutPreview.setObjectName("layoutPreview")
        self.frameControls = QtGui.QFrame(SetupJobForm)
        self.frameControls.setObjectName("frameControls")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frameControls)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnZoomIn = QtGui.QToolButton(self.frameControls)
        self.btnZoomIn.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.btnZoomIn.setFont(font)
        self.btnZoomIn.setObjectName("btnZoomIn")
        self.horizontalLayout_3.addWidget(self.btnZoomIn)
        self.btnZoomOut = QtGui.QToolButton(self.frameControls)
        self.btnZoomOut.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.btnZoomOut.setFont(font)
        self.btnZoomOut.setObjectName("btnZoomOut")
        self.horizontalLayout_3.addWidget(self.btnZoomOut)
        self.btnFit = QtGui.QToolButton(self.frameControls)
        self.btnFit.setMaximumSize(QtCore.QSize(24, 24))
        self.btnFit.setObjectName("btnFit")
        self.horizontalLayout_3.addWidget(self.btnFit)
        self.btnOne2one = QtGui.QToolButton(self.frameControls)
        self.btnOne2one.setMaximumSize(QtCore.QSize(24, 24))
        self.btnOne2one.setObjectName("btnOne2one")
        self.horizontalLayout_3.addWidget(self.btnOne2one)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spinFrameNum = QtGui.QSpinBox(self.frameControls)
        self.spinFrameNum.setMinimumSize(QtCore.QSize(100, 0))
        self.spinFrameNum.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinFrameNum.setMaximum(99999)
        self.spinFrameNum.setProperty("value", 99999)
        self.spinFrameNum.setObjectName("spinFrameNum")
        self.horizontalLayout_3.addWidget(self.spinFrameNum)
        self.btnBackLong = QtGui.QToolButton(self.frameControls)
        self.btnBackLong.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnBackLong.setFont(font)
        self.btnBackLong.setObjectName("btnBackLong")
        self.horizontalLayout_3.addWidget(self.btnBackLong)
        self.btnBackShort = QtGui.QToolButton(self.frameControls)
        self.btnBackShort.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnBackShort.setFont(font)
        self.btnBackShort.setObjectName("btnBackShort")
        self.horizontalLayout_3.addWidget(self.btnBackShort)
        self.btnBackSingle = QtGui.QToolButton(self.frameControls)
        self.btnBackSingle.setMinimumSize(QtCore.QSize(24, 24))
        self.btnBackSingle.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnBackSingle.setFont(font)
        self.btnBackSingle.setObjectName("btnBackSingle")
        self.horizontalLayout_3.addWidget(self.btnBackSingle)
        self.btnStop = QtGui.QToolButton(self.frameControls)
        self.btnStop.setMinimumSize(QtCore.QSize(24, 24))
        self.btnStop.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.btnFwdSingle = QtGui.QToolButton(self.frameControls)
        self.btnFwdSingle.setMinimumSize(QtCore.QSize(24, 24))
        self.btnFwdSingle.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnFwdSingle.setFont(font)
        self.btnFwdSingle.setObjectName("btnFwdSingle")
        self.horizontalLayout_3.addWidget(self.btnFwdSingle)
        self.btnFwdsShort = QtGui.QToolButton(self.frameControls)
        self.btnFwdsShort.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnFwdsShort.setFont(font)
        self.btnFwdsShort.setObjectName("btnFwdsShort")
        self.horizontalLayout_3.addWidget(self.btnFwdsShort)
        self.btnFwdsLong = QtGui.QToolButton(self.frameControls)
        self.btnFwdsLong.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.btnFwdsLong.setFont(font)
        self.btnFwdsLong.setObjectName("btnFwdsLong")
        self.horizontalLayout_3.addWidget(self.btnFwdsLong)
        self.btnNudgeU = QtGui.QToolButton(self.frameControls)
        self.btnNudgeU.setMinimumSize(QtCore.QSize(24, 24))
        self.btnNudgeU.setMaximumSize(QtCore.QSize(24, 16777215))
        self.btnNudgeU.setObjectName("btnNudgeU")
        self.horizontalLayout_3.addWidget(self.btnNudgeU)
        self.btnNudgeD = QtGui.QToolButton(self.frameControls)
        self.btnNudgeD.setMinimumSize(QtCore.QSize(24, 24))
        self.btnNudgeD.setMaximumSize(QtCore.QSize(24, 16777215))
        self.btnNudgeD.setObjectName("btnNudgeD")
        self.horizontalLayout_3.addWidget(self.btnNudgeD)
        self.layoutPreview.addWidget(self.frameControls)
        self.horizontalLayout.addLayout(self.layoutPreview)
        self.frameSetupTools = QtGui.QFrame(SetupJobForm)
        self.frameSetupTools.setMinimumSize(QtCore.QSize(260, 0))
        self.frameSetupTools.setMaximumSize(QtCore.QSize(260, 16777215))
        self.frameSetupTools.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSetupTools.setFrameShadow(QtGui.QFrame.Plain)
        self.frameSetupTools.setLineWidth(0)
        self.frameSetupTools.setObjectName("frameSetupTools")
        self.verticalLayout = QtGui.QVBoxLayout(self.frameSetupTools)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.frameSetupTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(260, 300))
        self.toolBox.setMaximumSize(QtCore.QSize(260, 16777215))
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.toolJob = QtGui.QWidget()
        self.toolJob.setGeometry(QtCore.QRect(0, 0, 260, 257))
        self.toolJob.setMaximumSize(QtCore.QSize(260, 16777215))
        self.toolJob.setObjectName("toolJob")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.toolJob)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblJobname = QtGui.QLabel(self.toolJob)
        self.lblJobname.setObjectName("lblJobname")
        self.verticalLayout_5.addWidget(self.lblJobname)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblJobName = QtGui.QLabel(self.toolJob)
        self.lblJobName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobName.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobName.setObjectName("lblJobName")
        self.horizontalLayout_7.addWidget(self.lblJobName)
        self.btnChangeJobName = QtGui.QPushButton(self.toolJob)
        self.btnChangeJobName.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnChangeJobName.setObjectName("btnChangeJobName")
        self.horizontalLayout_7.addWidget(self.btnChangeJobName)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.lblOutputDir = QtGui.QLabel(self.toolJob)
        self.lblOutputDir.setObjectName("lblOutputDir")
        self.verticalLayout_5.addWidget(self.lblOutputDir)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblProjectDir = QtGui.QLabel(self.toolJob)
        self.lblProjectDir.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblProjectDir.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblProjectDir.setObjectName("lblProjectDir")
        self.horizontalLayout_5.addWidget(self.lblProjectDir)
        self.btnChooseDir = QtGui.QPushButton(self.toolJob)
        self.btnChooseDir.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnChooseDir.setObjectName("btnChooseDir")
        self.horizontalLayout_5.addWidget(self.btnChooseDir)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.label_3 = QtGui.QLabel(self.toolJob)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.lblJobDir = QtGui.QLabel(self.toolJob)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblJobDir.setFont(font)
        self.lblJobDir.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobDir.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobDir.setObjectName("lblJobDir")
        self.verticalLayout_5.addWidget(self.lblJobDir)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblFilmTypeHeading = QtGui.QLabel(self.toolJob)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilmTypeHeading.sizePolicy().hasHeightForWidth())
        self.lblFilmTypeHeading.setSizePolicy(sizePolicy)
        self.lblFilmTypeHeading.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lblFilmTypeHeading.setObjectName("lblFilmTypeHeading")
        self.horizontalLayout_6.addWidget(self.lblFilmTypeHeading)
        self.lblFilmType = QtGui.QLabel(self.toolJob)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lblFilmType.setFont(font)
        self.lblFilmType.setObjectName("lblFilmType")
        self.horizontalLayout_6.addWidget(self.lblFilmType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.btnChangeFilm = QtGui.QPushButton(self.toolJob)
        self.btnChangeFilm.setObjectName("btnChangeFilm")
        self.verticalLayout_5.addWidget(self.btnChangeFilm)
        self.toolBox.addItem(self.toolJob, "")
        self.toolExposure = QtGui.QWidget()
        self.toolExposure.setGeometry(QtCore.QRect(0, 0, 260, 161))
        self.toolExposure.setObjectName("toolExposure")
        self.gridLayout_2 = QtGui.QGridLayout(self.toolExposure)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinGainR = QtGui.QDoubleSpinBox(self.toolExposure)
        self.spinGainR.setDecimals(3)
        self.spinGainR.setMinimum(0.1)
        self.spinGainR.setMaximum(8.0)
        self.spinGainR.setSingleStep(0.05)
        self.spinGainR.setProperty("value", 1.5)
        self.spinGainR.setObjectName("spinGainR")
        self.gridLayout_2.addWidget(self.spinGainR, 1, 1, 1, 1)
        self.lblShutter = QtGui.QLabel(self.toolExposure)
        self.lblShutter.setObjectName("lblShutter")
        self.gridLayout_2.addWidget(self.lblShutter, 0, 0, 1, 1)
        self.lblGainB = QtGui.QLabel(self.toolExposure)
        self.lblGainB.setObjectName("lblGainB")
        self.gridLayout_2.addWidget(self.lblGainB, 2, 0, 1, 1)
        self.spinShutter = QtGui.QSpinBox(self.toolExposure)
        self.spinShutter.setMinimum(100)
        self.spinShutter.setMaximum(99999)
        self.spinShutter.setSingleStep(25)
        self.spinShutter.setProperty("value", 2500)
        self.spinShutter.setObjectName("spinShutter")
        self.gridLayout_2.addWidget(self.spinShutter, 0, 1, 1, 1)
        self.spinGainB = QtGui.QDoubleSpinBox(self.toolExposure)
        self.spinGainB.setDecimals(3)
        self.spinGainB.setMinimum(0.1)
        self.spinGainB.setMaximum(8.0)
        self.spinGainB.setSingleStep(0.05)
        self.spinGainB.setProperty("value", 1.5)
        self.spinGainB.setObjectName("spinGainB")
        self.gridLayout_2.addWidget(self.spinGainB, 2, 1, 1, 1)
        self.lblGainR = QtGui.QLabel(self.toolExposure)
        self.lblGainR.setObjectName("lblGainR")
        self.gridLayout_2.addWidget(self.lblGainR, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.chkShowClipped = QtGui.QCheckBox(self.toolExposure)
        self.chkShowClipped.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkShowClipped.setObjectName("chkShowClipped")
        self.gridLayout_2.addWidget(self.chkShowClipped, 3, 0, 1, 1)
        self.toolBox.addItem(self.toolExposure, "")
        self.toolPerforation = QtGui.QWidget()
        self.toolPerforation.setGeometry(QtCore.QRect(0, 0, 260, 160))
        self.toolPerforation.setObjectName("toolPerforation")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.toolPerforation)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupEdgeReference = QtGui.QGroupBox(self.toolPerforation)
        self.groupEdgeReference.setFlat(True)
        self.groupEdgeReference.setObjectName("groupEdgeReference")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupEdgeReference)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioTopEdge = QtGui.QRadioButton(self.groupEdgeReference)
        self.radioTopEdge.setChecked(True)
        self.radioTopEdge.setObjectName("radioTopEdge")
        self.gridLayout_4.addWidget(self.radioTopEdge, 0, 0, 1, 1)
        self.radioBottomEdge = QtGui.QRadioButton(self.groupEdgeReference)
        self.radioBottomEdge.setObjectName("radioBottomEdge")
        self.gridLayout_4.addWidget(self.radioBottomEdge, 0, 1, 1, 1)
        self.radioTopBotEdge = QtGui.QRadioButton(self.groupEdgeReference)
        self.radioTopBotEdge.setObjectName("radioTopBotEdge")
        self.gridLayout_4.addWidget(self.radioTopBotEdge, 1, 0, 1, 1)
        self.checkLeftEdge = QtGui.QCheckBox(self.groupEdgeReference)
        self.checkLeftEdge.setObjectName("checkLeftEdge")
        self.gridLayout_4.addWidget(self.checkLeftEdge, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupEdgeReference)
        self.lblPerforationInfo = QtGui.QLabel(self.toolPerforation)
        self.lblPerforationInfo.setObjectName("lblPerforationInfo")
        self.verticalLayout_7.addWidget(self.lblPerforationInfo)
        self.toolBox.addItem(self.toolPerforation, "")
        self.toolTransport = QtGui.QWidget()
        self.toolTransport.setGeometry(QtCore.QRect(0, 0, 260, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolTransport.sizePolicy().hasHeightForWidth())
        self.toolTransport.setSizePolicy(sizePolicy)
        self.toolTransport.setObjectName("toolTransport")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.toolTransport)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameCalibrateTransport = QtGui.QFrame(self.toolTransport)
        self.frameCalibrateTransport.setEnabled(False)
        self.frameCalibrateTransport.setObjectName("frameCalibrateTransport")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frameCalibrateTransport)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblCalibrate = QtGui.QLabel(self.frameCalibrateTransport)
        self.lblCalibrate.setObjectName("lblCalibrate")
        self.horizontalLayout_2.addWidget(self.lblCalibrate)
        self.btnCalibBack = QtGui.QPushButton(self.frameCalibrateTransport)
        self.btnCalibBack.setObjectName("btnCalibBack")
        self.horizontalLayout_2.addWidget(self.btnCalibBack)
        self.btnCalibFwd = QtGui.QPushButton(self.frameCalibrateTransport)
        self.btnCalibFwd.setObjectName("btnCalibFwd")
        self.horizontalLayout_2.addWidget(self.btnCalibFwd)
        self.verticalLayout_3.addWidget(self.frameCalibrateTransport)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblShortJump = QtGui.QLabel(self.toolTransport)
        self.lblShortJump.setObjectName("lblShortJump")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblShortJump)
        self.spinShortJump = QtGui.QSpinBox(self.toolTransport)
        self.spinShortJump.setPrefix("")
        self.spinShortJump.setMinimum(10)
        self.spinShortJump.setMaximum(40)
        self.spinShortJump.setProperty("value", 18)
        self.spinShortJump.setObjectName("spinShortJump")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinShortJump)
        self.spinLongJump = QtGui.QSpinBox(self.toolTransport)
        self.spinLongJump.setMinimum(20)
        self.spinLongJump.setMaximum(500)
        self.spinLongJump.setSingleStep(20)
        self.spinLongJump.setProperty("value", 180)
        self.spinLongJump.setObjectName("spinLongJump")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinLongJump)
        self.lblLongJump = QtGui.QLabel(self.toolTransport)
        self.lblLongJump.setObjectName("lblLongJump")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblLongJump)
        self.lblStepsPixel_2 = QtGui.QLabel(self.toolTransport)
        self.lblStepsPixel_2.setObjectName("lblStepsPixel_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lblStepsPixel_2)
        self.lblStepsPixel = QtGui.QLabel(self.toolTransport)
        self.lblStepsPixel.setObjectName("lblStepsPixel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lblStepsPixel)
        self.lblPixelsStep = QtGui.QLabel(self.toolTransport)
        self.lblPixelsStep.setObjectName("lblPixelsStep")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblPixelsStep)
        self.lblStepsFrame = QtGui.QLabel(self.toolTransport)
        self.lblStepsFrame.setObjectName("lblStepsFrame")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblStepsFrame)
        self.verticalLayout_3.addLayout(self.formLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.toolBox.addItem(self.toolTransport, "")
        self.toolCrop = QtGui.QWidget()
        self.toolCrop.setEnabled(False)
        self.toolCrop.setGeometry(QtCore.QRect(0, 0, 260, 196))
        self.toolCrop.setObjectName("toolCrop")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.toolCrop)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblCeopPos = QtGui.QLabel(self.toolCrop)
        self.lblCeopPos.setObjectName("lblCeopPos")
        self.gridLayout.addWidget(self.lblCeopPos, 0, 0, 1, 1)
        self.lblCropSize = QtGui.QLabel(self.toolCrop)
        self.lblCropSize.setObjectName("lblCropSize")
        self.gridLayout.addWidget(self.lblCropSize, 1, 0, 1, 1)
        self.spinCropH = QtGui.QSpinBox(self.toolCrop)
        self.spinCropH.setMinimumSize(QtCore.QSize(64, 0))
        self.spinCropH.setMaximumSize(QtCore.QSize(64, 16777215))
        self.spinCropH.setMaximum(1944)
        self.spinCropH.setProperty("value", 1944)
        self.spinCropH.setObjectName("spinCropH")
        self.gridLayout.addWidget(self.spinCropH, 1, 3, 1, 1)
        self.spinCropX = QtGui.QSpinBox(self.toolCrop)
        self.spinCropX.setMinimumSize(QtCore.QSize(64, 0))
        self.spinCropX.setMaximumSize(QtCore.QSize(64, 16777215))
        self.spinCropX.setMinimum(-1200)
        self.spinCropX.setMaximum(1200)
        self.spinCropX.setProperty("value", 0)
        self.spinCropX.setObjectName("spinCropX")
        self.gridLayout.addWidget(self.spinCropX, 0, 1, 1, 1)
        self.spinCropW = QtGui.QSpinBox(self.toolCrop)
        self.spinCropW.setMinimumSize(QtCore.QSize(64, 0))
        self.spinCropW.setMaximumSize(QtCore.QSize(64, 16777215))
        self.spinCropW.setMaximum(2592)
        self.spinCropW.setProperty("value", 2592)
        self.spinCropW.setObjectName("spinCropW")
        self.gridLayout.addWidget(self.spinCropW, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.toolCrop)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.toolCrop)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.spinCropY = QtGui.QSpinBox(self.toolCrop)
        self.spinCropY.setMinimumSize(QtCore.QSize(64, 0))
        self.spinCropY.setMaximumSize(QtCore.QSize(64, 16777215))
        self.spinCropY.setMinimum(-900)
        self.spinCropY.setMaximum(900)
        self.spinCropY.setProperty("value", 0)
        self.spinCropY.setObjectName("spinCropY")
        self.gridLayout.addWidget(self.spinCropY, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cmbAspectFix = QtGui.QComboBox(self.toolCrop)
        self.cmbAspectFix.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbAspectFix.setMaximumSize(QtCore.QSize(64, 16777215))
        self.cmbAspectFix.setObjectName("cmbAspectFix")
        self.cmbAspectFix.addItem("")
        self.cmbAspectFix.addItem("")
        self.cmbAspectFix.addItem("")
        self.gridLayout_5.addWidget(self.cmbAspectFix, 1, 1, 1, 1)
        self.lblAspectFix = QtGui.QLabel(self.toolCrop)
        self.lblAspectFix.setObjectName("lblAspectFix")
        self.gridLayout_5.addWidget(self.lblAspectFix, 1, 0, 1, 1)
        self.btnAutoCrop = QtGui.QPushButton(self.toolCrop)
        self.btnAutoCrop.setObjectName("btnAutoCrop")
        self.gridLayout_5.addWidget(self.btnAutoCrop, 3, 1, 1, 1)
        self.spinHistArea = QtGui.QSpinBox(self.toolCrop)
        self.spinHistArea.setMinimum(10)
        self.spinHistArea.setMaximum(90)
        self.spinHistArea.setProperty("value", 75)
        self.spinHistArea.setObjectName("spinHistArea")
        self.gridLayout_5.addWidget(self.spinHistArea, 2, 1, 1, 1)
        self.lblHistogramArea = QtGui.QLabel(self.toolCrop)
        self.lblHistogramArea.setObjectName("lblHistogramArea")
        self.gridLayout_5.addWidget(self.lblHistogramArea, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.toolBox.addItem(self.toolCrop, "")
        self.verticalLayout.addWidget(self.toolBox)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.lblHistogram = QtGui.QLabel(self.frameSetupTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistogram.sizePolicy().hasHeightForWidth())
        self.lblHistogram.setSizePolicy(sizePolicy)
        self.lblHistogram.setMinimumSize(QtCore.QSize(256, 128))
        self.lblHistogram.setMaximumSize(QtCore.QSize(256, 128))
        self.lblHistogram.setScaledContents(True)
        self.lblHistogram.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHistogram.setObjectName("lblHistogram")
        self.verticalLayout.addWidget(self.lblHistogram)
        self.horizontalLayout.addWidget(self.frameSetupTools)

        self.retranslateUi(SetupJobForm)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SetupJobForm)
        SetupJobForm.setTabOrder(self.btnChangeJobName, self.btnChooseDir)
        SetupJobForm.setTabOrder(self.btnChooseDir, self.btnChangeFilm)
        SetupJobForm.setTabOrder(self.btnChangeFilm, self.spinShutter)
        SetupJobForm.setTabOrder(self.spinShutter, self.spinGainR)
        SetupJobForm.setTabOrder(self.spinGainR, self.spinGainB)
        SetupJobForm.setTabOrder(self.spinGainB, self.radioTopEdge)
        SetupJobForm.setTabOrder(self.radioTopEdge, self.radioBottomEdge)
        SetupJobForm.setTabOrder(self.radioBottomEdge, self.radioTopBotEdge)
        SetupJobForm.setTabOrder(self.radioTopBotEdge, self.checkLeftEdge)
        SetupJobForm.setTabOrder(self.checkLeftEdge, self.btnCalibBack)
        SetupJobForm.setTabOrder(self.btnCalibBack, self.btnCalibFwd)
        SetupJobForm.setTabOrder(self.btnCalibFwd, self.spinShortJump)
        SetupJobForm.setTabOrder(self.spinShortJump, self.spinLongJump)
        SetupJobForm.setTabOrder(self.spinLongJump, self.spinCropX)
        SetupJobForm.setTabOrder(self.spinCropX, self.spinCropY)
        SetupJobForm.setTabOrder(self.spinCropY, self.spinCropW)
        SetupJobForm.setTabOrder(self.spinCropW, self.spinCropH)
        SetupJobForm.setTabOrder(self.spinCropH, self.cmbAspectFix)
        SetupJobForm.setTabOrder(self.cmbAspectFix, self.btnAutoCrop)
        SetupJobForm.setTabOrder(self.btnAutoCrop, self.btnZoomIn)
        SetupJobForm.setTabOrder(self.btnZoomIn, self.btnZoomOut)
        SetupJobForm.setTabOrder(self.btnZoomOut, self.btnFit)
        SetupJobForm.setTabOrder(self.btnFit, self.btnOne2one)
        SetupJobForm.setTabOrder(self.btnOne2one, self.spinFrameNum)
        SetupJobForm.setTabOrder(self.spinFrameNum, self.btnBackLong)
        SetupJobForm.setTabOrder(self.btnBackLong, self.btnBackShort)
        SetupJobForm.setTabOrder(self.btnBackShort, self.btnBackSingle)
        SetupJobForm.setTabOrder(self.btnBackSingle, self.btnStop)
        SetupJobForm.setTabOrder(self.btnStop, self.btnFwdSingle)
        SetupJobForm.setTabOrder(self.btnFwdSingle, self.btnFwdsShort)
        SetupJobForm.setTabOrder(self.btnFwdsShort, self.btnFwdsLong)
        SetupJobForm.setTabOrder(self.btnFwdsLong, self.btnNudgeU)
        SetupJobForm.setTabOrder(self.btnNudgeU, self.btnNudgeD)

    def retranslateUi(self, SetupJobForm):
        SetupJobForm.setWindowTitle(QtGui.QApplication.translate("SetupJobForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomIn.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomIn.setText(QtGui.QApplication.translate("SetupJobForm", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomOut.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomOut.setText(QtGui.QApplication.translate("SetupJobForm", "–", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFit.setText(QtGui.QApplication.translate("SetupJobForm", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOne2one.setText(QtGui.QApplication.translate("SetupJobForm", "1:1", None, QtGui.QApplication.UnicodeUTF8))
        self.spinFrameNum.setPrefix(QtGui.QApplication.translate("SetupJobForm", "Frame: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackLong.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Move film back(long)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackLong.setText(QtGui.QApplication.translate("SetupJobForm", "<<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackShort.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Move film back(short)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackShort.setText(QtGui.QApplication.translate("SetupJobForm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackSingle.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Move film back 1 frame", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackSingle.setText(QtGui.QApplication.translate("SetupJobForm", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setText(QtGui.QApplication.translate("SetupJobForm", "◊", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdSingle.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Move film forwards 1 frame", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdSingle.setText(QtGui.QApplication.translate("SetupJobForm", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsShort.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Move film forwards(short)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsShort.setText(QtGui.QApplication.translate("SetupJobForm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsLong.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Move film forwards(long)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsLong.setText(QtGui.QApplication.translate("SetupJobForm", ">>>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeU.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Nudge film up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeU.setText(QtGui.QApplication.translate("SetupJobForm", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeD.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Nudge film down", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeD.setText(QtGui.QApplication.translate("SetupJobForm", "↓", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJobname.setText(QtGui.QApplication.translate("SetupJobForm", "Job name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJobName.setText(QtGui.QApplication.translate("SetupJobForm", "Job Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChangeJobName.setText(QtGui.QApplication.translate("SetupJobForm", "Change...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputDir.setText(QtGui.QApplication.translate("SetupJobForm", "Projects directory", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectDir.setText(QtGui.QApplication.translate("SetupJobForm", "project dir", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChooseDir.setText(QtGui.QApplication.translate("SetupJobForm", "Change...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SetupJobForm", "Job outputs to", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJobDir.setText(QtGui.QApplication.translate("SetupJobForm", "Job directory", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilmTypeHeading.setText(QtGui.QApplication.translate("SetupJobForm", "Film Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilmType.setText(QtGui.QApplication.translate("SetupJobForm", "Super 8", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChangeFilm.setText(QtGui.QApplication.translate("SetupJobForm", "Change film type", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolJob), QtGui.QApplication.translate("SetupJobForm", "&Job Details", None, QtGui.QApplication.UnicodeUTF8))
        self.lblShutter.setText(QtGui.QApplication.translate("SetupJobForm", "Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGainB.setText(QtGui.QApplication.translate("SetupJobForm", "Blue gain", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGainR.setText(QtGui.QApplication.translate("SetupJobForm", "Red gain", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowClipped.setText(QtGui.QApplication.translate("SetupJobForm", "Show clipped pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolExposure), QtGui.QApplication.translate("SetupJobForm", "E&xposure", None, QtGui.QApplication.UnicodeUTF8))
        self.groupEdgeReference.setTitle(QtGui.QApplication.translate("SetupJobForm", "Edges to use as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopEdge.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Use top edge of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopEdge.setText(QtGui.QApplication.translate("SetupJobForm", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBottomEdge.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Use bottom edge of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBottomEdge.setText(QtGui.QApplication.translate("SetupJobForm", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopBotEdge.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Use top & bottom edges of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopBotEdge.setText(QtGui.QApplication.translate("SetupJobForm", "Top and bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLeftEdge.setToolTip(QtGui.QApplication.translate("SetupJobForm", "Use left edge of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLeftEdge.setText(QtGui.QApplication.translate("SetupJobForm", "Left edge", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerforationInfo.setText(QtGui.QApplication.translate("SetupJobForm", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Double click in film<br/>perforation on preview</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolPerforation), QtGui.QApplication.translate("SetupJobForm", "&Perforation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalibrate.setText(QtGui.QApplication.translate("SetupJobForm", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCalibBack.setText(QtGui.QApplication.translate("SetupJobForm", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCalibFwd.setText(QtGui.QApplication.translate("SetupJobForm", "Fwds", None, QtGui.QApplication.UnicodeUTF8))
        self.lblShortJump.setText(QtGui.QApplication.translate("SetupJobForm", "Short jump", None, QtGui.QApplication.UnicodeUTF8))
        self.spinShortJump.setSuffix(QtGui.QApplication.translate("SetupJobForm", " frames", None, QtGui.QApplication.UnicodeUTF8))
        self.spinLongJump.setSuffix(QtGui.QApplication.translate("SetupJobForm", " frames", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLongJump.setText(QtGui.QApplication.translate("SetupJobForm", "Long jump", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepsPixel_2.setText(QtGui.QApplication.translate("SetupJobForm", "285", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepsPixel.setText(QtGui.QApplication.translate("SetupJobForm", "3.5", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPixelsStep.setText(QtGui.QApplication.translate("SetupJobForm", "Pixels/Step", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepsFrame.setText(QtGui.QApplication.translate("SetupJobForm", "Steps/Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolTransport), QtGui.QApplication.translate("SetupJobForm", "&Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCeopPos.setText(QtGui.QApplication.translate("SetupJobForm", "Crop position", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCropSize.setText(QtGui.QApplication.translate("SetupJobForm", "Crop Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SetupJobForm", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SetupJobForm", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAspectFix.setItemText(0, QtGui.QApplication.translate("SetupJobForm", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAspectFix.setItemText(1, QtGui.QApplication.translate("SetupJobForm", "4:3", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAspectFix.setItemText(2, QtGui.QApplication.translate("SetupJobForm", "16:9", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAspectFix.setText(QtGui.QApplication.translate("SetupJobForm", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAutoCrop.setText(QtGui.QApplication.translate("SetupJobForm", "Auto Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.spinHistArea.setSuffix(QtGui.QApplication.translate("SetupJobForm", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHistogramArea.setText(QtGui.QApplication.translate("SetupJobForm", "Histogram Area", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolCrop), QtGui.QApplication.translate("SetupJobForm", "&Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHistogram.setText(QtGui.QApplication.translate("SetupJobForm", "Histogram", None, QtGui.QApplication.UnicodeUTF8))

