# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telecineui.ui'
#
# Created: Wed Mar 11 11:55:37 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TelecinePreview(object):
    def setupUi(self, TelecinePreview):
        TelecinePreview.setObjectName("TelecinePreview")
        TelecinePreview.resize(897, 660)
        self.centralwidget = QtGui.QWidget(TelecinePreview)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tabSetup = QtGui.QWidget()
        self.tabSetup.setObjectName("tabSetup")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabSetup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.previewDisplay = QtGui.QScrollArea(self.tabSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewDisplay.sizePolicy().hasHeightForWidth())
        self.previewDisplay.setSizePolicy(sizePolicy)
        self.previewDisplay.setMinimumSize(QtCore.QSize(400, 300))
        self.previewDisplay.setWidgetResizable(True)
        self.previewDisplay.setObjectName("previewDisplay")
        self.previewArea = QtGui.QWidget()
        self.previewArea.setGeometry(QtCore.QRect(0, 0, 577, 461))
        self.previewArea.setMaximumSize(QtCore.QSize(577, 461))
        self.previewArea.setObjectName("previewArea")
        self.lblPreviewDisplay = QtGui.QLabel(self.previewArea)
        self.lblPreviewDisplay.setGeometry(QtCore.QRect(0, 0, 2592, 1944))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPreviewDisplay.sizePolicy().hasHeightForWidth())
        self.lblPreviewDisplay.setSizePolicy(sizePolicy)
        self.lblPreviewDisplay.setScaledContents(True)
        self.lblPreviewDisplay.setObjectName("lblPreviewDisplay")
        self.previewDisplay.setWidget(self.previewArea)
        self.verticalLayout_3.addWidget(self.previewDisplay)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnZoomInPreview = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.btnZoomInPreview.setFont(font)
        self.btnZoomInPreview.setObjectName("btnZoomInPreview")
        self.horizontalLayout_3.addWidget(self.btnZoomInPreview)
        self.btnZoomOutPreview = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.btnZoomOutPreview.setFont(font)
        self.btnZoomOutPreview.setObjectName("btnZoomOutPreview")
        self.horizontalLayout_3.addWidget(self.btnZoomOutPreview)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spinFrameNum = QtGui.QSpinBox(self.tabSetup)
        self.spinFrameNum.setMinimumSize(QtCore.QSize(100, 0))
        self.spinFrameNum.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinFrameNum.setMaximum(99999)
        self.spinFrameNum.setProperty("value", 99999)
        self.spinFrameNum.setObjectName("spinFrameNum")
        self.horizontalLayout_3.addWidget(self.spinFrameNum)
        self.btnBackLong = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.btnBackLong.setFont(font)
        self.btnBackLong.setObjectName("btnBackLong")
        self.horizontalLayout_3.addWidget(self.btnBackLong)
        self.btnBackShort = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnBackShort.setFont(font)
        self.btnBackShort.setObjectName("btnBackShort")
        self.horizontalLayout_3.addWidget(self.btnBackShort)
        self.btnBackSingle = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnBackSingle.setFont(font)
        self.btnBackSingle.setObjectName("btnBackSingle")
        self.horizontalLayout_3.addWidget(self.btnBackSingle)
        self.btnStop = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.btnFwdSingle = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnFwdSingle.setFont(font)
        self.btnFwdSingle.setObjectName("btnFwdSingle")
        self.horizontalLayout_3.addWidget(self.btnFwdSingle)
        self.btnFwdsShort = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnFwdsShort.setFont(font)
        self.btnFwdsShort.setObjectName("btnFwdsShort")
        self.horizontalLayout_3.addWidget(self.btnFwdsShort)
        self.btnFwdsLong = QtGui.QToolButton(self.tabSetup)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.btnFwdsLong.setFont(font)
        self.btnFwdsLong.setObjectName("btnFwdsLong")
        self.horizontalLayout_3.addWidget(self.btnFwdsLong)
        self.btnNudgeU = QtGui.QToolButton(self.tabSetup)
        self.btnNudgeU.setObjectName("btnNudgeU")
        self.horizontalLayout_3.addWidget(self.btnNudgeU)
        self.btnNudgeD = QtGui.QToolButton(self.tabSetup)
        self.btnNudgeD.setObjectName("btnNudgeD")
        self.horizontalLayout_3.addWidget(self.btnNudgeD)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.frameSetupTools = QtGui.QFrame(self.tabSetup)
        self.frameSetupTools.setMinimumSize(QtCore.QSize(256, 0))
        self.frameSetupTools.setMaximumSize(QtCore.QSize(256, 16777215))
        self.frameSetupTools.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSetupTools.setFrameShadow(QtGui.QFrame.Plain)
        self.frameSetupTools.setLineWidth(0)
        self.frameSetupTools.setObjectName("frameSetupTools")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frameSetupTools)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.toolBox = QtGui.QToolBox(self.frameSetupTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(256, 300))
        self.toolBox.setMaximumSize(QtCore.QSize(256, 16777215))
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.toolJob = QtGui.QWidget()
        self.toolJob.setGeometry(QtCore.QRect(0, 0, 240, 229))
        self.toolJob.setObjectName("toolJob")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.toolJob)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblJobname = QtGui.QLabel(self.toolJob)
        self.lblJobname.setObjectName("lblJobname")
        self.verticalLayout_6.addWidget(self.lblJobname)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblJobName = QtGui.QLabel(self.toolJob)
        self.lblJobName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobName.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobName.setObjectName("lblJobName")
        self.horizontalLayout_7.addWidget(self.lblJobName)
        self.btnChangeJobName = QtGui.QPushButton(self.toolJob)
        self.btnChangeJobName.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnChangeJobName.setObjectName("btnChangeJobName")
        self.horizontalLayout_7.addWidget(self.btnChangeJobName)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.lblOutputDir = QtGui.QLabel(self.toolJob)
        self.lblOutputDir.setObjectName("lblOutputDir")
        self.verticalLayout_6.addWidget(self.lblOutputDir)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblProjectDir = QtGui.QLabel(self.toolJob)
        self.lblProjectDir.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblProjectDir.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblProjectDir.setObjectName("lblProjectDir")
        self.horizontalLayout_5.addWidget(self.lblProjectDir)
        self.btnChooseDir = QtGui.QPushButton(self.toolJob)
        self.btnChooseDir.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnChooseDir.setObjectName("btnChooseDir")
        self.horizontalLayout_5.addWidget(self.btnChooseDir)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_3 = QtGui.QLabel(self.toolJob)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.lblJobDir = QtGui.QLabel(self.toolJob)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblJobDir.setFont(font)
        self.lblJobDir.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobDir.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobDir.setObjectName("lblJobDir")
        self.verticalLayout_6.addWidget(self.lblJobDir)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblFilmTypeHeading = QtGui.QLabel(self.toolJob)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilmTypeHeading.sizePolicy().hasHeightForWidth())
        self.lblFilmTypeHeading.setSizePolicy(sizePolicy)
        self.lblFilmTypeHeading.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lblFilmTypeHeading.setObjectName("lblFilmTypeHeading")
        self.horizontalLayout_6.addWidget(self.lblFilmTypeHeading)
        self.lblFilmType = QtGui.QLabel(self.toolJob)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lblFilmType.setFont(font)
        self.lblFilmType.setObjectName("lblFilmType")
        self.horizontalLayout_6.addWidget(self.lblFilmType)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.btnChangeFilm = QtGui.QPushButton(self.toolJob)
        self.btnChangeFilm.setObjectName("btnChangeFilm")
        self.verticalLayout_6.addWidget(self.btnChangeFilm)
        self.toolBox.addItem(self.toolJob, "")
        self.toolPerforation = QtGui.QWidget()
        self.toolPerforation.setGeometry(QtCore.QRect(0, 0, 256, 174))
        self.toolPerforation.setObjectName("toolPerforation")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.toolPerforation)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnDetectPerf = QtGui.QPushButton(self.toolPerforation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDetectPerf.sizePolicy().hasHeightForWidth())
        self.btnDetectPerf.setSizePolicy(sizePolicy)
        self.btnDetectPerf.setObjectName("btnDetectPerf")
        self.verticalLayout_7.addWidget(self.btnDetectPerf)
        self.lblPerforationInfo = QtGui.QLabel(self.toolPerforation)
        self.lblPerforationInfo.setObjectName("lblPerforationInfo")
        self.verticalLayout_7.addWidget(self.lblPerforationInfo)
        self.groupEdgeReference = QtGui.QGroupBox(self.toolPerforation)
        self.groupEdgeReference.setFlat(True)
        self.groupEdgeReference.setObjectName("groupEdgeReference")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupEdgeReference)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioTopEdge = QtGui.QRadioButton(self.groupEdgeReference)
        self.radioTopEdge.setChecked(True)
        self.radioTopEdge.setObjectName("radioTopEdge")
        self.gridLayout_4.addWidget(self.radioTopEdge, 0, 0, 1, 1)
        self.radioBottomEdge = QtGui.QRadioButton(self.groupEdgeReference)
        self.radioBottomEdge.setObjectName("radioBottomEdge")
        self.gridLayout_4.addWidget(self.radioBottomEdge, 0, 1, 1, 1)
        self.radioTopBotEdge = QtGui.QRadioButton(self.groupEdgeReference)
        self.radioTopBotEdge.setObjectName("radioTopBotEdge")
        self.gridLayout_4.addWidget(self.radioTopBotEdge, 1, 0, 1, 1)
        self.checkLeftEdge = QtGui.QCheckBox(self.groupEdgeReference)
        self.checkLeftEdge.setObjectName("checkLeftEdge")
        self.gridLayout_4.addWidget(self.checkLeftEdge, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupEdgeReference)
        self.toolBox.addItem(self.toolPerforation, "")
        self.toolExposure = QtGui.QWidget()
        self.toolExposure.setGeometry(QtCore.QRect(0, 0, 256, 136))
        self.toolExposure.setObjectName("toolExposure")
        self.gridLayout_2 = QtGui.QGridLayout(self.toolExposure)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinGainR = QtGui.QDoubleSpinBox(self.toolExposure)
        self.spinGainR.setDecimals(3)
        self.spinGainR.setMinimum(0.1)
        self.spinGainR.setMaximum(8.0)
        self.spinGainR.setProperty("value", 1.0)
        self.spinGainR.setObjectName("spinGainR")
        self.gridLayout_2.addWidget(self.spinGainR, 1, 1, 1, 1)
        self.lblShutter = QtGui.QLabel(self.toolExposure)
        self.lblShutter.setObjectName("lblShutter")
        self.gridLayout_2.addWidget(self.lblShutter, 0, 0, 1, 1)
        self.lblGainB = QtGui.QLabel(self.toolExposure)
        self.lblGainB.setObjectName("lblGainB")
        self.gridLayout_2.addWidget(self.lblGainB, 2, 0, 1, 1)
        self.spinShutter = QtGui.QSpinBox(self.toolExposure)
        self.spinShutter.setMinimum(100)
        self.spinShutter.setMaximum(9999)
        self.spinShutter.setProperty("value", 1500)
        self.spinShutter.setObjectName("spinShutter")
        self.gridLayout_2.addWidget(self.spinShutter, 0, 1, 1, 1)
        self.spinGainB = QtGui.QDoubleSpinBox(self.toolExposure)
        self.spinGainB.setDecimals(3)
        self.spinGainB.setMinimum(0.1)
        self.spinGainB.setMaximum(8.0)
        self.spinGainB.setProperty("value", 1.0)
        self.spinGainB.setObjectName("spinGainB")
        self.gridLayout_2.addWidget(self.spinGainB, 2, 1, 1, 1)
        self.lblGainR = QtGui.QLabel(self.toolExposure)
        self.lblGainR.setObjectName("lblGainR")
        self.gridLayout_2.addWidget(self.lblGainR, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.toolBox.addItem(self.toolExposure, "")
        self.toolTransport = QtGui.QWidget()
        self.toolTransport.setGeometry(QtCore.QRect(0, 0, 256, 210))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolTransport.sizePolicy().hasHeightForWidth())
        self.toolTransport.setSizePolicy(sizePolicy)
        self.toolTransport.setObjectName("toolTransport")
        self.gridLayout_3 = QtGui.QGridLayout(self.toolTransport)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblCalibrate = QtGui.QLabel(self.toolTransport)
        self.lblCalibrate.setObjectName("lblCalibrate")
        self.gridLayout_3.addWidget(self.lblCalibrate, 0, 0, 1, 1)
        self.btnCalibFwd = QtGui.QPushButton(self.toolTransport)
        self.btnCalibFwd.setObjectName("btnCalibFwd")
        self.gridLayout_3.addWidget(self.btnCalibFwd, 0, 1, 1, 1)
        self.btnCalibBack = QtGui.QPushButton(self.toolTransport)
        self.btnCalibBack.setObjectName("btnCalibBack")
        self.gridLayout_3.addWidget(self.btnCalibBack, 1, 1, 1, 1)
        self.lblPixelsStep = QtGui.QLabel(self.toolTransport)
        self.lblPixelsStep.setObjectName("lblPixelsStep")
        self.gridLayout_3.addWidget(self.lblPixelsStep, 2, 0, 1, 1)
        self.spinShortJump = QtGui.QSpinBox(self.toolTransport)
        self.spinShortJump.setPrefix("")
        self.spinShortJump.setMinimum(10)
        self.spinShortJump.setMaximum(40)
        self.spinShortJump.setProperty("value", 18)
        self.spinShortJump.setObjectName("spinShortJump")
        self.gridLayout_3.addWidget(self.spinShortJump, 4, 1, 1, 1)
        self.lblStepsPixel = QtGui.QLabel(self.toolTransport)
        self.lblStepsPixel.setObjectName("lblStepsPixel")
        self.gridLayout_3.addWidget(self.lblStepsPixel, 2, 1, 1, 1)
        self.lblStepsFrame = QtGui.QLabel(self.toolTransport)
        self.lblStepsFrame.setObjectName("lblStepsFrame")
        self.gridLayout_3.addWidget(self.lblStepsFrame, 3, 0, 1, 1)
        self.lblStepsPixel_2 = QtGui.QLabel(self.toolTransport)
        self.lblStepsPixel_2.setObjectName("lblStepsPixel_2")
        self.gridLayout_3.addWidget(self.lblStepsPixel_2, 3, 1, 1, 1)
        self.lblShortJump = QtGui.QLabel(self.toolTransport)
        self.lblShortJump.setObjectName("lblShortJump")
        self.gridLayout_3.addWidget(self.lblShortJump, 4, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 7, 0, 1, 1)
        self.lblLongJump = QtGui.QLabel(self.toolTransport)
        self.lblLongJump.setObjectName("lblLongJump")
        self.gridLayout_3.addWidget(self.lblLongJump, 5, 0, 1, 1)
        self.spinLongJump = QtGui.QSpinBox(self.toolTransport)
        self.spinLongJump.setMinimum(20)
        self.spinLongJump.setMaximum(500)
        self.spinLongJump.setSingleStep(20)
        self.spinLongJump.setProperty("value", 180)
        self.spinLongJump.setObjectName("spinLongJump")
        self.gridLayout_3.addWidget(self.spinLongJump, 5, 1, 1, 1)
        self.toolBox.addItem(self.toolTransport, "")
        self.toolCrop = QtGui.QWidget()
        self.toolCrop.setGeometry(QtCore.QRect(0, 0, 256, 234))
        self.toolCrop.setObjectName("toolCrop")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.toolCrop)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblCropWidth = QtGui.QLabel(self.toolCrop)
        self.lblCropWidth.setObjectName("lblCropWidth")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblCropWidth)
        self.spinCropWidth = QtGui.QSpinBox(self.toolCrop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCropWidth.sizePolicy().hasHeightForWidth())
        self.spinCropWidth.setSizePolicy(sizePolicy)
        self.spinCropWidth.setMinimum(400)
        self.spinCropWidth.setMaximum(2500)
        self.spinCropWidth.setSingleStep(5)
        self.spinCropWidth.setProperty("value", 400)
        self.spinCropWidth.setObjectName("spinCropWidth")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinCropWidth)
        self.btnCropLeft = QtGui.QToolButton(self.toolCrop)
        self.btnCropLeft.setMinimumSize(QtCore.QSize(32, 32))
        self.btnCropLeft.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.btnCropLeft.setFont(font)
        self.btnCropLeft.setObjectName("btnCropLeft")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.btnCropLeft)
        self.lblCropWidth_2 = QtGui.QLabel(self.toolCrop)
        self.lblCropWidth_2.setObjectName("lblCropWidth_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCropWidth_2)
        self.spinCropWidth_2 = QtGui.QSpinBox(self.toolCrop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCropWidth_2.sizePolicy().hasHeightForWidth())
        self.spinCropWidth_2.setSizePolicy(sizePolicy)
        self.spinCropWidth_2.setMinimum(400)
        self.spinCropWidth_2.setMaximum(2500)
        self.spinCropWidth_2.setSingleStep(5)
        self.spinCropWidth_2.setProperty("value", 400)
        self.spinCropWidth_2.setObjectName("spinCropWidth_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinCropWidth_2)
        self.lblAspectFix = QtGui.QLabel(self.toolCrop)
        self.lblAspectFix.setObjectName("lblAspectFix")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblAspectFix)
        self.cmbAspectFix = QtGui.QComboBox(self.toolCrop)
        self.cmbAspectFix.setObjectName("cmbAspectFix")
        self.cmbAspectFix.addItem("")
        self.cmbAspectFix.addItem("")
        self.cmbAspectFix.addItem("")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cmbAspectFix)
        self.btnCropRight = QtGui.QToolButton(self.toolCrop)
        self.btnCropRight.setMinimumSize(QtCore.QSize(32, 32))
        self.btnCropRight.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.btnCropRight.setFont(font)
        self.btnCropRight.setObjectName("btnCropRight")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.btnCropRight)
        self.btnCropUp = QtGui.QToolButton(self.toolCrop)
        self.btnCropUp.setMinimumSize(QtCore.QSize(32, 32))
        self.btnCropUp.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.btnCropUp.setFont(font)
        self.btnCropUp.setObjectName("btnCropUp")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.btnCropUp)
        self.btnCropDown = QtGui.QToolButton(self.toolCrop)
        self.btnCropDown.setMinimumSize(QtCore.QSize(32, 32))
        self.btnCropDown.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.btnCropDown.setFont(font)
        self.btnCropDown.setObjectName("btnCropDown")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.btnCropDown)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.label = QtGui.QLabel(self.toolCrop)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.toolCrop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.toolBox.addItem(self.toolCrop, "")
        self.toolFX = QtGui.QWidget()
        self.toolFX.setGeometry(QtCore.QRect(0, 0, 256, 215))
        self.toolFX.setObjectName("toolFX")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.toolFX)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chkColourBalEffect = QtGui.QCheckBox(self.toolFX)
        self.chkColourBalEffect.setObjectName("chkColourBalEffect")
        self.verticalLayout_4.addWidget(self.chkColourBalEffect)
        self.frameColourBalance = QtGui.QFrame(self.toolFX)
        self.frameColourBalance.setEnabled(False)
        self.frameColourBalance.setObjectName("frameColourBalance")
        self.gridLayout_5 = QtGui.QGridLayout(self.frameColourBalance)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinBalGreen = QtGui.QSpinBox(self.frameColourBalance)
        self.spinBalGreen.setMaximum(256)
        self.spinBalGreen.setObjectName("spinBalGreen")
        self.gridLayout_5.addWidget(self.spinBalGreen, 1, 2, 1, 1)
        self.spinBalRed = QtGui.QSpinBox(self.frameColourBalance)
        self.spinBalRed.setMaximum(256)
        self.spinBalRed.setObjectName("spinBalRed")
        self.gridLayout_5.addWidget(self.spinBalRed, 0, 2, 1, 1)
        self.sliderBalV = QtGui.QSlider(self.frameColourBalance)
        self.sliderBalV.setMaximum(256)
        self.sliderBalV.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBalV.setObjectName("sliderBalV")
        self.gridLayout_5.addWidget(self.sliderBalV, 4, 1, 1, 1)
        self.lblBalBlue = QtGui.QLabel(self.frameColourBalance)
        self.lblBalBlue.setObjectName("lblBalBlue")
        self.gridLayout_5.addWidget(self.lblBalBlue, 2, 0, 1, 1)
        self.lblBalGreen = QtGui.QLabel(self.frameColourBalance)
        self.lblBalGreen.setObjectName("lblBalGreen")
        self.gridLayout_5.addWidget(self.lblBalGreen, 1, 0, 1, 1)
        self.spinBalBlue = QtGui.QSpinBox(self.frameColourBalance)
        self.spinBalBlue.setMaximum(256)
        self.spinBalBlue.setObjectName("spinBalBlue")
        self.gridLayout_5.addWidget(self.spinBalBlue, 2, 2, 1, 1)
        self.sliderBalBlue = QtGui.QSlider(self.frameColourBalance)
        self.sliderBalBlue.setMaximum(256)
        self.sliderBalBlue.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBalBlue.setObjectName("sliderBalBlue")
        self.gridLayout_5.addWidget(self.sliderBalBlue, 2, 1, 1, 1)
        self.sliderBalGreen = QtGui.QSlider(self.frameColourBalance)
        self.sliderBalGreen.setMaximum(256)
        self.sliderBalGreen.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBalGreen.setObjectName("sliderBalGreen")
        self.gridLayout_5.addWidget(self.sliderBalGreen, 1, 1, 1, 1)
        self.spinBalU = QtGui.QSpinBox(self.frameColourBalance)
        self.spinBalU.setMaximum(256)
        self.spinBalU.setObjectName("spinBalU")
        self.gridLayout_5.addWidget(self.spinBalU, 3, 2, 1, 1)
        self.lblBalRed = QtGui.QLabel(self.frameColourBalance)
        self.lblBalRed.setObjectName("lblBalRed")
        self.gridLayout_5.addWidget(self.lblBalRed, 0, 0, 1, 1)
        self.sliderBalU = QtGui.QSlider(self.frameColourBalance)
        self.sliderBalU.setMaximum(256)
        self.sliderBalU.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBalU.setObjectName("sliderBalU")
        self.gridLayout_5.addWidget(self.sliderBalU, 3, 1, 1, 1)
        self.lblBalU = QtGui.QLabel(self.frameColourBalance)
        self.lblBalU.setObjectName("lblBalU")
        self.gridLayout_5.addWidget(self.lblBalU, 3, 0, 1, 1)
        self.spinBalV = QtGui.QSpinBox(self.frameColourBalance)
        self.spinBalV.setMaximum(256)
        self.spinBalV.setObjectName("spinBalV")
        self.gridLayout_5.addWidget(self.spinBalV, 4, 2, 1, 1)
        self.lblBalV = QtGui.QLabel(self.frameColourBalance)
        self.lblBalV.setObjectName("lblBalV")
        self.gridLayout_5.addWidget(self.lblBalV, 4, 0, 1, 1)
        self.sliderBalRed = QtGui.QSlider(self.frameColourBalance)
        self.sliderBalRed.setMaximum(256)
        self.sliderBalRed.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBalRed.setObjectName("sliderBalRed")
        self.gridLayout_5.addWidget(self.sliderBalRed, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frameColourBalance)
        spacerItem6 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.toolBox.addItem(self.toolFX, "")
        self.verticalLayout_8.addWidget(self.toolBox)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.lblHistogram = QtGui.QLabel(self.frameSetupTools)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistogram.sizePolicy().hasHeightForWidth())
        self.lblHistogram.setSizePolicy(sizePolicy)
        self.lblHistogram.setMinimumSize(QtCore.QSize(256, 128))
        self.lblHistogram.setMaximumSize(QtCore.QSize(256, 128))
        self.lblHistogram.setScaledContents(True)
        self.lblHistogram.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHistogram.setObjectName("lblHistogram")
        self.verticalLayout_8.addWidget(self.lblHistogram)
        self.horizontalLayout_4.addWidget(self.frameSetupTools)
        self.tabs.addTab(self.tabSetup, "")
        self.tabRun = QtGui.QWidget()
        self.tabRun.setObjectName("tabRun")
        self.tabs.addTab(self.tabRun, "")
        self.tabPreview = QtGui.QWidget()
        self.tabPreview.setObjectName("tabPreview")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabPreview)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(self.tabPreview)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblPreview = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPreview.sizePolicy().hasHeightForWidth())
        self.lblPreview.setSizePolicy(sizePolicy)
        self.lblPreview.setMinimumSize(QtCore.QSize(400, 300))
        self.lblPreview.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblPreview.setObjectName("lblPreview")
        self.verticalLayout.addWidget(self.lblPreview)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sliderPreviewZoom = QtGui.QSlider(self.frame)
        self.sliderPreviewZoom.setMinimum(10)
        self.sliderPreviewZoom.setMaximum(40)
        self.sliderPreviewZoom.setSingleStep(1)
        self.sliderPreviewZoom.setPageStep(4)
        self.sliderPreviewZoom.setProperty("value", 10)
        self.sliderPreviewZoom.setTracking(True)
        self.sliderPreviewZoom.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPreviewZoom.setTickPosition(QtGui.QSlider.NoTicks)
        self.sliderPreviewZoom.setObjectName("sliderPreviewZoom")
        self.horizontalLayout_2.addWidget(self.sliderPreviewZoom)
        self.btnPreviewL = QtGui.QToolButton(self.frame)
        self.btnPreviewL.setObjectName("btnPreviewL")
        self.horizontalLayout_2.addWidget(self.btnPreviewL)
        self.btnPreviewU = QtGui.QToolButton(self.frame)
        self.btnPreviewU.setObjectName("btnPreviewU")
        self.horizontalLayout_2.addWidget(self.btnPreviewU)
        self.btnPreviewD = QtGui.QToolButton(self.frame)
        self.btnPreviewD.setObjectName("btnPreviewD")
        self.horizontalLayout_2.addWidget(self.btnPreviewD)
        self.btnPreviewR = QtGui.QToolButton(self.frame)
        self.btnPreviewR.setObjectName("btnPreviewR")
        self.horizontalLayout_2.addWidget(self.btnPreviewR)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame)
        self.framePreviewTools = QtGui.QFrame(self.tabPreview)
        self.framePreviewTools.setMinimumSize(QtCore.QSize(256, 0))
        self.framePreviewTools.setMaximumSize(QtCore.QSize(256, 16777215))
        self.framePreviewTools.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePreviewTools.setFrameShadow(QtGui.QFrame.Plain)
        self.framePreviewTools.setLineWidth(0)
        self.framePreviewTools.setObjectName("framePreviewTools")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.framePreviewTools)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnAutoExpose = QtGui.QPushButton(self.framePreviewTools)
        self.btnAutoExpose.setObjectName("btnAutoExpose")
        self.verticalLayout_9.addWidget(self.btnAutoExpose)
        self.lblAWBMode = QtGui.QLabel(self.framePreviewTools)
        self.lblAWBMode.setObjectName("lblAWBMode")
        self.verticalLayout_9.addWidget(self.lblAWBMode)
        self.cmbAWBMode = QtGui.QComboBox(self.framePreviewTools)
        self.cmbAWBMode.setObjectName("cmbAWBMode")
        self.verticalLayout_9.addWidget(self.cmbAWBMode)
        self.lblExpInfo = QtGui.QLabel(self.framePreviewTools)
        self.lblExpInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblExpInfo.setWordWrap(True)
        self.lblExpInfo.setObjectName("lblExpInfo")
        self.verticalLayout_9.addWidget(self.lblExpInfo)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.chkSaveDefaultExp = QtGui.QCheckBox(self.framePreviewTools)
        self.chkSaveDefaultExp.setObjectName("chkSaveDefaultExp")
        self.verticalLayout_9.addWidget(self.chkSaveDefaultExp)
        self.btnPreviewSave = QtGui.QPushButton(self.framePreviewTools)
        self.btnPreviewSave.setObjectName("btnPreviewSave")
        self.verticalLayout_9.addWidget(self.btnPreviewSave)
        self.horizontalLayout.addWidget(self.framePreviewTools)
        self.tabs.addTab(self.tabPreview, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)
        TelecinePreview.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TelecinePreview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 19))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        TelecinePreview.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TelecinePreview)
        self.statusbar.setObjectName("statusbar")
        TelecinePreview.setStatusBar(self.statusbar)
        self.action_Quit = QtGui.QAction(TelecinePreview)
        self.action_Quit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_Quit.setMenuRole(QtGui.QAction.QuitRole)
        self.action_Quit.setObjectName("action_Quit")
        self.menu_File.addAction(self.action_Quit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.lblBalBlue.setBuddy(self.spinBalBlue)
        self.lblBalGreen.setBuddy(self.spinBalGreen)
        self.lblBalRed.setBuddy(self.spinBalRed)
        self.lblBalU.setBuddy(self.spinBalU)
        self.lblBalV.setBuddy(self.spinBalV)

        self.retranslateUi(TelecinePreview)
        self.tabs.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("triggered()"), TelecinePreview.close)
        QtCore.QObject.connect(self.chkColourBalEffect, QtCore.SIGNAL("toggled(bool)"), self.frameColourBalance.setEnabled)
        QtCore.QObject.connect(self.sliderBalRed, QtCore.SIGNAL("valueChanged(int)"), self.spinBalRed.setValue)
        QtCore.QObject.connect(self.sliderBalGreen, QtCore.SIGNAL("valueChanged(int)"), self.spinBalGreen.setValue)
        QtCore.QObject.connect(self.sliderBalBlue, QtCore.SIGNAL("valueChanged(int)"), self.spinBalBlue.setValue)
        QtCore.QObject.connect(self.sliderBalU, QtCore.SIGNAL("valueChanged(int)"), self.spinBalU.setValue)
        QtCore.QObject.connect(self.sliderBalV, QtCore.SIGNAL("valueChanged(int)"), self.spinBalV.setValue)
        QtCore.QObject.connect(self.spinBalRed, QtCore.SIGNAL("valueChanged(int)"), self.sliderBalRed.setValue)
        QtCore.QObject.connect(self.spinBalGreen, QtCore.SIGNAL("valueChanged(int)"), self.sliderBalGreen.setValue)
        QtCore.QObject.connect(self.spinBalBlue, QtCore.SIGNAL("valueChanged(int)"), self.sliderBalBlue.setValue)
        QtCore.QObject.connect(self.spinBalU, QtCore.SIGNAL("valueChanged(int)"), self.sliderBalU.setValue)
        QtCore.QObject.connect(self.spinBalV, QtCore.SIGNAL("valueChanged(int)"), self.sliderBalV.setValue)
        QtCore.QMetaObject.connectSlotsByName(TelecinePreview)
        TelecinePreview.setTabOrder(self.tabs, self.previewDisplay)
        TelecinePreview.setTabOrder(self.previewDisplay, self.btnZoomInPreview)
        TelecinePreview.setTabOrder(self.btnZoomInPreview, self.btnZoomOutPreview)
        TelecinePreview.setTabOrder(self.btnZoomOutPreview, self.btnBackLong)
        TelecinePreview.setTabOrder(self.btnBackLong, self.btnBackShort)
        TelecinePreview.setTabOrder(self.btnBackShort, self.btnBackSingle)
        TelecinePreview.setTabOrder(self.btnBackSingle, self.btnStop)
        TelecinePreview.setTabOrder(self.btnStop, self.btnFwdSingle)
        TelecinePreview.setTabOrder(self.btnFwdSingle, self.btnFwdsShort)
        TelecinePreview.setTabOrder(self.btnFwdsShort, self.btnFwdsLong)
        TelecinePreview.setTabOrder(self.btnFwdsLong, self.btnNudgeU)
        TelecinePreview.setTabOrder(self.btnNudgeU, self.btnNudgeD)
        TelecinePreview.setTabOrder(self.btnNudgeD, self.btnChooseDir)
        TelecinePreview.setTabOrder(self.btnChooseDir, self.btnChangeFilm)
        TelecinePreview.setTabOrder(self.btnChangeFilm, self.btnDetectPerf)
        TelecinePreview.setTabOrder(self.btnDetectPerf, self.radioTopEdge)
        TelecinePreview.setTabOrder(self.radioTopEdge, self.radioBottomEdge)
        TelecinePreview.setTabOrder(self.radioBottomEdge, self.radioTopBotEdge)
        TelecinePreview.setTabOrder(self.radioTopBotEdge, self.checkLeftEdge)
        TelecinePreview.setTabOrder(self.checkLeftEdge, self.spinShutter)
        TelecinePreview.setTabOrder(self.spinShutter, self.spinGainR)
        TelecinePreview.setTabOrder(self.spinGainR, self.spinGainB)
        TelecinePreview.setTabOrder(self.spinGainB, self.btnCalibFwd)
        TelecinePreview.setTabOrder(self.btnCalibFwd, self.btnCalibBack)
        TelecinePreview.setTabOrder(self.btnCalibBack, self.spinShortJump)
        TelecinePreview.setTabOrder(self.spinShortJump, self.spinLongJump)
        TelecinePreview.setTabOrder(self.spinLongJump, self.spinCropWidth)
        TelecinePreview.setTabOrder(self.spinCropWidth, self.spinCropWidth_2)
        TelecinePreview.setTabOrder(self.spinCropWidth_2, self.cmbAspectFix)
        TelecinePreview.setTabOrder(self.cmbAspectFix, self.btnCropLeft)
        TelecinePreview.setTabOrder(self.btnCropLeft, self.btnCropRight)
        TelecinePreview.setTabOrder(self.btnCropRight, self.btnCropUp)
        TelecinePreview.setTabOrder(self.btnCropUp, self.btnCropDown)
        TelecinePreview.setTabOrder(self.btnCropDown, self.chkColourBalEffect)
        TelecinePreview.setTabOrder(self.chkColourBalEffect, self.sliderBalRed)
        TelecinePreview.setTabOrder(self.sliderBalRed, self.spinBalRed)
        TelecinePreview.setTabOrder(self.spinBalRed, self.sliderBalGreen)
        TelecinePreview.setTabOrder(self.sliderBalGreen, self.spinBalGreen)
        TelecinePreview.setTabOrder(self.spinBalGreen, self.sliderBalBlue)
        TelecinePreview.setTabOrder(self.sliderBalBlue, self.spinBalBlue)
        TelecinePreview.setTabOrder(self.spinBalBlue, self.sliderBalU)
        TelecinePreview.setTabOrder(self.sliderBalU, self.spinBalU)
        TelecinePreview.setTabOrder(self.spinBalU, self.sliderBalV)
        TelecinePreview.setTabOrder(self.sliderBalV, self.spinBalV)
        TelecinePreview.setTabOrder(self.spinBalV, self.sliderPreviewZoom)
        TelecinePreview.setTabOrder(self.sliderPreviewZoom, self.btnPreviewL)
        TelecinePreview.setTabOrder(self.btnPreviewL, self.btnPreviewU)
        TelecinePreview.setTabOrder(self.btnPreviewU, self.btnPreviewD)
        TelecinePreview.setTabOrder(self.btnPreviewD, self.btnPreviewR)
        TelecinePreview.setTabOrder(self.btnPreviewR, self.btnAutoExpose)
        TelecinePreview.setTabOrder(self.btnAutoExpose, self.cmbAWBMode)
        TelecinePreview.setTabOrder(self.cmbAWBMode, self.chkSaveDefaultExp)
        TelecinePreview.setTabOrder(self.chkSaveDefaultExp, self.btnPreviewSave)

    def retranslateUi(self, TelecinePreview):
        TelecinePreview.setWindowTitle(QtGui.QApplication.translate("TelecinePreview", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPreviewDisplay.setText(QtGui.QApplication.translate("TelecinePreview", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomInPreview.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomInPreview.setText(QtGui.QApplication.translate("TelecinePreview", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomOutPreview.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.btnZoomOutPreview.setText(QtGui.QApplication.translate("TelecinePreview", "–", None, QtGui.QApplication.UnicodeUTF8))
        self.spinFrameNum.setPrefix(QtGui.QApplication.translate("TelecinePreview", "Frame: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackLong.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move film back(long)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackLong.setText(QtGui.QApplication.translate("TelecinePreview", "<<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackShort.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move film back(short)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackShort.setText(QtGui.QApplication.translate("TelecinePreview", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackSingle.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move film back 1 frame", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackSingle.setText(QtGui.QApplication.translate("TelecinePreview", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setText(QtGui.QApplication.translate("TelecinePreview", "◊", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdSingle.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move film forwards 1 frame", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdSingle.setText(QtGui.QApplication.translate("TelecinePreview", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsShort.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move film forwards(short)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsShort.setText(QtGui.QApplication.translate("TelecinePreview", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsLong.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move film forwards(long)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFwdsLong.setText(QtGui.QApplication.translate("TelecinePreview", ">>>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeU.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Nudge film up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeU.setText(QtGui.QApplication.translate("TelecinePreview", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeD.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Nudge film down", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNudgeD.setText(QtGui.QApplication.translate("TelecinePreview", "↓", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJobname.setText(QtGui.QApplication.translate("TelecinePreview", "Job name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJobName.setText(QtGui.QApplication.translate("TelecinePreview", "Job Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChangeJobName.setText(QtGui.QApplication.translate("TelecinePreview", "Change...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputDir.setText(QtGui.QApplication.translate("TelecinePreview", "Projects directory", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectDir.setText(QtGui.QApplication.translate("TelecinePreview", "project dir", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChooseDir.setText(QtGui.QApplication.translate("TelecinePreview", "Change...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TelecinePreview", "Job outputs to", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJobDir.setText(QtGui.QApplication.translate("TelecinePreview", "Job directory", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilmTypeHeading.setText(QtGui.QApplication.translate("TelecinePreview", "Film Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilmType.setText(QtGui.QApplication.translate("TelecinePreview", "Super 8", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChangeFilm.setText(QtGui.QApplication.translate("TelecinePreview", "Change film type", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolJob), QtGui.QApplication.translate("TelecinePreview", "&Job Details", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDetectPerf.setText(QtGui.QApplication.translate("TelecinePreview", "Detect Perforation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPerforationInfo.setText(QtGui.QApplication.translate("TelecinePreview", "<html><head/><body><p><span style=\" font-weight:600;\">Perforation found:</span></p><p>100x100</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupEdgeReference.setTitle(QtGui.QApplication.translate("TelecinePreview", "Edges to use as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopEdge.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Use top edge of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopEdge.setText(QtGui.QApplication.translate("TelecinePreview", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBottomEdge.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Use bottom edge of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBottomEdge.setText(QtGui.QApplication.translate("TelecinePreview", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopBotEdge.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Use top & bottom edges of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTopBotEdge.setText(QtGui.QApplication.translate("TelecinePreview", "Top and bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLeftEdge.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Use left edge of perforation as reference", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLeftEdge.setText(QtGui.QApplication.translate("TelecinePreview", "Left edge", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolPerforation), QtGui.QApplication.translate("TelecinePreview", "&Perforation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblShutter.setText(QtGui.QApplication.translate("TelecinePreview", "Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGainB.setText(QtGui.QApplication.translate("TelecinePreview", "Blue gain", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGainR.setText(QtGui.QApplication.translate("TelecinePreview", "Red gain", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolExposure), QtGui.QApplication.translate("TelecinePreview", "E&xposure", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalibrate.setText(QtGui.QApplication.translate("TelecinePreview", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCalibFwd.setText(QtGui.QApplication.translate("TelecinePreview", "Fwds", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCalibBack.setText(QtGui.QApplication.translate("TelecinePreview", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPixelsStep.setText(QtGui.QApplication.translate("TelecinePreview", "Pixels/Step", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepsPixel.setText(QtGui.QApplication.translate("TelecinePreview", "3.5", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepsFrame.setText(QtGui.QApplication.translate("TelecinePreview", "Steps/Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepsPixel_2.setText(QtGui.QApplication.translate("TelecinePreview", "285", None, QtGui.QApplication.UnicodeUTF8))
        self.lblShortJump.setText(QtGui.QApplication.translate("TelecinePreview", "Short jump", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLongJump.setText(QtGui.QApplication.translate("TelecinePreview", "Long jump", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolTransport), QtGui.QApplication.translate("TelecinePreview", "&Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCropWidth.setText(QtGui.QApplication.translate("TelecinePreview", "Crop Width", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCropLeft.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Move crop left", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCropLeft.setText(QtGui.QApplication.translate("TelecinePreview", "←", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCropWidth_2.setText(QtGui.QApplication.translate("TelecinePreview", "Crop Height", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAspectFix.setText(QtGui.QApplication.translate("TelecinePreview", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAspectFix.setItemText(0, QtGui.QApplication.translate("TelecinePreview", "4:3", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAspectFix.setItemText(1, QtGui.QApplication.translate("TelecinePreview", "16:9", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAspectFix.setItemText(2, QtGui.QApplication.translate("TelecinePreview", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCropRight.setText(QtGui.QApplication.translate("TelecinePreview", "→", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCropUp.setText(QtGui.QApplication.translate("TelecinePreview", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCropDown.setText(QtGui.QApplication.translate("TelecinePreview", "↓", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TelecinePreview", "Crop Area details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TelecinePreview", "+100,-100 400x900", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolCrop), QtGui.QApplication.translate("TelecinePreview", "&Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.chkColourBalEffect.setText(QtGui.QApplication.translate("TelecinePreview", "Apply Colour Balance Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBalBlue.setText(QtGui.QApplication.translate("TelecinePreview", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBalGreen.setText(QtGui.QApplication.translate("TelecinePreview", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBalRed.setText(QtGui.QApplication.translate("TelecinePreview", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBalU.setText(QtGui.QApplication.translate("TelecinePreview", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBalV.setText(QtGui.QApplication.translate("TelecinePreview", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolFX), QtGui.QApplication.translate("TelecinePreview", "&Effects", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHistogram.setText(QtGui.QApplication.translate("TelecinePreview", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tabSetup), QtGui.QApplication.translate("TelecinePreview", "Setup Telecine", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tabRun), QtGui.QApplication.translate("TelecinePreview", "Run Telecine", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPreview.setText(QtGui.QApplication.translate("TelecinePreview", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Note</span><span style=\" font-size:12pt;\">: Preview only visible on </span></p><p align=\"center\"><span style=\" font-size:12pt;\">Raspberry Pi HDMI display</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sliderPreviewZoom.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Zoom preview", None, QtGui.QApplication.UnicodeUTF8))
        self.sliderPreviewZoom.setAccessibleName(QtGui.QApplication.translate("TelecinePreview", "Zoom Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewL.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Preview left", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewL.setText(QtGui.QApplication.translate("TelecinePreview", "←", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewU.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Preview up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewU.setText(QtGui.QApplication.translate("TelecinePreview", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewD.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Preview down", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewD.setText(QtGui.QApplication.translate("TelecinePreview", "↓", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewR.setToolTip(QtGui.QApplication.translate("TelecinePreview", "Preview right", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewR.setText(QtGui.QApplication.translate("TelecinePreview", "→", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAutoExpose.setText(QtGui.QApplication.translate("TelecinePreview", "Auto Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAWBMode.setText(QtGui.QApplication.translate("TelecinePreview", "White Balance mode", None, QtGui.QApplication.UnicodeUTF8))
        self.lblExpInfo.setText(QtGui.QApplication.translate("TelecinePreview", "<html><head/><body><p>Exposure info</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSaveDefaultExp.setText(QtGui.QApplication.translate("TelecinePreview", "Set as default", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreviewSave.setText(QtGui.QApplication.translate("TelecinePreview", "Save Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tabPreview), QtGui.QApplication.translate("TelecinePreview", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("TelecinePreview", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("TelecinePreview", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("TelecinePreview", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

